// Test-only entry — bundles pure schedule helpers without mounting React.
export {
  parseTimeRange,
  teacherKey,
  normalizeV2,
  migrateOld,
  migrateV1toV2,
  upgrade,
  overlaps,
  buildScheduleIndexes,
  maxEndForPlacement,
  roomConflictsIndexed,
  teacherBusyIndexed,
  computeTabBlockMeta,
  dataSignature,
  layoutLanes,
  formatDayRange,
  classScheduleLines,
  sortCatalogForByClassView,
  isLocalDevHost,
  isPreviewHost,
  isRemoteSyncEnabled,
  PRODUCTION_HOST,
  LIVE_V1_SEED,
  LIVE_SEED_TAG,
} from "./App.jsx";